[package]
name = "basket-math"
version = "0.1.0"
authors = ["William Chen <wchen298@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
